CREATE TABLE "area_demographics" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "area_demographics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"zipCode" varchar(10) NOT NULL,
	"county_fips" varchar(5) NOT NULL,
	"total_population" integer NOT NULL,
	"median_income" integer DEFAULT 0,
	"median_rent" integer DEFAULT 0,
	"labor_force" integer DEFAULT 0,
	"unemployed" integer DEFAULT 0,
	"bachelor_degree_holders" integer DEFAULT 0,
	"masters_degree_holders" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
